### ISSUE TITLE
when env variables should be set for running shadowRun

### ISSUE THREAD

**Issue by mastermind1981** [Trunkplatform/lazybones-dropwizard-turbo#1]
Hi,

Thank you for your great job and effort.

I want to know how to set env variables to be set before running shadowRun? for example setting the db connection properties?

Thank you in advance,

**Comment by mrserverless** [comment]
Hi @mastermind1981 thanks for trying this out.

The environment variables are set in the server that you are running in. You would do that once in the beginning, and not meant to set them every time you run the application, unless something changes. See http://12factor.net/config for the thinking behind this.

As to how to set the env vars, you can use `export DB_URL=` on baremetal Unix, for Heroku you can use [Config Vars](https://devcenter.heroku.com/articles/config-vars) and for Docker [ENV](https://docs.docker.com/reference/run/#env-environment-variables) work in similar fashion

**Comment by mastermind1981** [comment]
thank you

**Comment by mrserverless** [comment]
Closing for now. Let me know if you come across any issues using Env Vars
